"""empty message

Revision ID: 15cee0a36974
Revises: 3f54f742c407
Create Date: 2026-07-23 10:15:13.031113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cee0a36974'
down_revision = '3f54f742c407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_job_cost', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('stock_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_type', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('total_job_cost')

    # ### end Alembic commands ###
