"""updated Null

Revision ID: 291f9708b70b
Revises: 15cee0a36974
Create Date: 2026-07-23 10:26:14.926715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291f9708b70b'
down_revision = '15cee0a36974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('customer', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(), nullable=False),
    sa.Column('total_job_cost', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
