"""Added all models

Revision ID: 3f54f742c407
Revises: e89d371ec64d
Create Date: 2026-07-15 20:18:39.529103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f54f742c407'
down_revision = 'e89d371ec64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stock_type', sa.String(), nullable=False),
    sa.Column('unit_measure', sa.String(), nullable=False),
    sa.Column('distributor', sa.String(), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=20, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('quantity_purchased', sa.Numeric(precision=20, scale=5), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=20, scale=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_lots_material_id_materials')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reorder_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_reorder_requests_material_id_materials')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reorder_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_material_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('material_lot_id', sa.Integer(), nullable=True),
    sa.Column('quantity_used', sa.Numeric(precision=20, scale=5), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_material_usages_job_id_jobs')),
    sa.ForeignKeyConstraint(['material_lot_id'], ['material_lots.id'], name=op.f('fk_job_material_usages_material_lot_id_material_lots')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labor_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_labor_entries_job_id_jobs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_labor_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    op.drop_table('labor_entries')
    op.drop_table('job_material_usages')
    op.drop_table('reorder_requests')
    op.drop_table('material_lots')
    op.drop_table('jobs')
    op.drop_table('materials')
    # ### end Alembic commands ###
