"""worked on cascade-5

Revision ID: 9668352c6fc3
Revises: aada7c4026dc
Create Date: 2026-07-23 22:43:07.586835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9668352c6fc3'
down_revision = 'aada7c4026dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labor_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_labor_entries_job_id_jobs'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_labor_entries_job_id_jobs'), 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labor_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_labor_entries_job_id_jobs'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_labor_entries_job_id_jobs'), 'jobs', ['job_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
