"""updated schema and decorator functions on job model

Revision ID: 9d96e6fe83ee
Revises: b25f9021ffae
Create Date: 2026-07-29 11:35:03.886814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d96e6fe83ee'
down_revision = 'b25f9021ffae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('total_job_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_job_cost', sa.NUMERIC(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
