"""worked on cascade-4

Revision ID: aada7c4026dc
Revises: 291f9708b70b
Create Date: 2026-07-23 12:12:53.691675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aada7c4026dc'
down_revision = '291f9708b70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labor_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_labor_entries_job_id_jobs'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_labor_entries_job_id_jobs'), 'jobs', ['job_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labor_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_labor_entries_job_id_jobs'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_labor_entries_job_id_jobs'), 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###
