"""updated material schema

Revision ID: b25f9021ffae
Revises: 9668352c6fc3
Create Date: 2026-07-27 11:52:43.204394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25f9021ffae'
down_revision = '9668352c6fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_material_sku', ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_constraint('uq_material_sku', type_='unique')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
